import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  androidBibleSidebar: [
    'intro',
    'roadmap',
    {
      type: 'category',
      label: 'Part I - Kotlin Foundations',
      collapsed: false,
      items: [
        'kotlin/why-kotlin',
        {
          type: 'category',
          label: 'Types and control flow',
          collapsed: false,
          items: [
            {type: 'doc', id: 'kotlin/types-and-control-flow', label: 'Chapter overview'},
            'kotlin/types-and-variables',
            'kotlin/expressions-and-control-flow',
            'kotlin/equality',
            'kotlin/smart-casts',
            'kotlin/types-control-android',
          ],
        },
        'kotlin/null-safety',
        {
          type: 'category',
          label: 'Functions and functional Kotlin',
          collapsed: true,
          items: [
            {type: 'doc', id: 'kotlin/functions-overview', label: 'Chapter overview'},
            'kotlin/functions',
            'kotlin/lambdas',
            'kotlin/higher-order-functions',
            'kotlin/inline-functions',
            'kotlin/reified-types',
            'kotlin/functional-kotlin-android',
            'kotlin/functional-kotlin-interview',
          ],
        },
        {
          type: 'category',
          label: 'Classes and type modeling',
          collapsed: true,
          items: [
            {type: 'doc', id: 'kotlin/classes-overview', label: 'Chapter overview'},
            'kotlin/constructors-init-properties',
            'kotlin/inheritance-interfaces',
            'kotlin/objects-companions',
            'kotlin/data-enum-sealed',
            'kotlin/classes-android-interview',
            'kotlin/value-classes',
          ],
        },
        {
          type: 'category',
          label: 'Collections and advanced APIs',
          collapsed: true,
          items: [
            {type: 'doc', id: 'kotlin/collections-overview', label: 'Chapter overview'},
            'kotlin/collections',
            'kotlin/sequences',
            'kotlin/generics-variance',
            'kotlin/extensions-deep-dive',
            'kotlin/delegates-dsls',
            'kotlin/collections-android-interview',
          ],
        },
        {
          type: 'category',
          label: 'Coroutines and Flow',
          collapsed: true,
          items: [
            {type: 'doc', id: 'kotlin/coroutines-overview', label: 'Chapter overview'},
            'kotlin/coroutine-basics',
            'kotlin/structured-concurrency',
            'kotlin/dispatchers-context',
            'kotlin/flow',
            'kotlin/hot-flows-channels',
            'kotlin/coroutines-android-interview',
          ],
        },
        {
          type: 'category',
          label: 'Java interop and migration',
          collapsed: true,
          items: [
            {type: 'doc', id: 'kotlin/java-interop-overview', label: 'Chapter overview'},
            'kotlin/java-from-kotlin',
            'kotlin/kotlin-from-java',
            'kotlin/java-migration',
            'kotlin/java-interop-interview',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Part II - Platform and Builds',
      collapsed: true,
      items: [
        {type: 'doc', id: 'android/platform-build-overview', label: 'Chapter overview'},
        'android/system-architecture',
        'android/processes-startup',
        'android/art-dex-runtime',
        'android/binder-ipc',
        'android/components-lifecycle',
        'android/activities-tasks',
        'android/fragments',
        'android/resources-configuration',
        'android/gradle-build-system',
        'android/platform-interview',
      ],
    },
    {type: 'category', label: 'Parts III-X - Android to Architect', items: ['roadmap']},
  ],
};

export default sidebars;
