import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  androidBibleSidebar: [
    'intro',
    'roadmap',
    {
      type: 'category',
      label: 'Part I - Kotlin Foundations',
      collapsed: false,
      items: [
        'kotlin/why-kotlin',
        {
          type: 'category',
          label: 'Types and control flow',
          collapsed: false,
          items: [
            {type: 'doc', id: 'kotlin/types-and-control-flow', label: 'Chapter overview'},
            'kotlin/types-and-variables',
            'kotlin/expressions-and-control-flow',
            'kotlin/equality',
            'kotlin/smart-casts',
            'kotlin/types-control-android',
          ],
        },
        'kotlin/null-safety',
        'kotlin/string-manipulation-reference',
        {
          type: 'category',
          label: 'Functions and functional Kotlin',
          collapsed: true,
          items: [
            {type: 'doc', id: 'kotlin/functions-overview', label: 'Chapter overview'},
            'kotlin/functions',
            'kotlin/lambdas',
            'kotlin/higher-order-functions',
            'kotlin/inline-functions',
            'kotlin/reified-types',
            'kotlin/functional-kotlin-android',
            'kotlin/functional-kotlin-interview',
          ],
        },
        {
          type: 'category',
          label: 'Classes and type modeling',
          collapsed: true,
          items: [
            {type: 'doc', id: 'kotlin/classes-overview', label: 'Chapter overview'},
            'kotlin/constructors-init-properties',
            'kotlin/inheritance-interfaces',
            'kotlin/objects-companions',
            'kotlin/data-enum-sealed',
            'kotlin/classes-android-interview',
            'kotlin/value-classes',
          ],
        },
        {
          type: 'category',
          label: 'Kotlin Collections',
          collapsed: true,
          items: [
            {type: 'doc', id: 'kotlin/collections-overview', label: 'Chapter overview'},
            'kotlin/collection-hierarchy',
            'kotlin/collections',
            'kotlin/collection-access-search-filter',
            'kotlin/collection-sorting-aggregation',
            'kotlin/collection-grouping-association',
            'kotlin/collection-mutation-copying',
            'kotlin/collection-operations',
            'kotlin/sequences',
            'kotlin/collections-android-interview',
          ],
        },
        {
          type: 'category',
          label: 'Kotlin type system',
          collapsed: true,
          items: [
            'kotlin/generics-variance',
          ],
        },
        {
          type: 'category',
          label: 'Advanced Kotlin',
          collapsed: true,
          items: [
            'kotlin/extensions-deep-dive',
            'kotlin/delegates-dsls',
          ],
        },
        {
          type: 'category',
          label: 'Coroutines and Flow',
          collapsed: true,
          items: [
            {type: 'doc', id: 'kotlin/coroutines-overview', label: 'Chapter overview'},
            'kotlin/coroutine-basics',
            'kotlin/coroutine-execution-trace',
            'kotlin/structured-concurrency',
            'kotlin/cancellation-exceptions',
            'kotlin/dispatchers-context',
            'kotlin/flow',
            'kotlin/flow-pipeline',
            'kotlin/flow-backpressure',
            'kotlin/hot-flows-channels',
            'kotlin/state-events-delivery',
            'kotlin/coroutines-android-interview',
          ],
        },
        {
          type: 'category',
          label: 'Java interop and migration',
          collapsed: true,
          items: [
            {type: 'doc', id: 'kotlin/java-interop-overview', label: 'Chapter overview'},
            'kotlin/java-from-kotlin',
            'kotlin/kotlin-from-java',
            'kotlin/java-migration',
            'kotlin/java-interop-interview',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Part II - Platform and Builds',
      collapsed: true,
      items: [
        {type: 'doc', id: 'android/platform-build-overview', label: 'Chapter overview'},
        'android/system-architecture',
        'android/framework-system-services',
        'android/linux-sandbox',
        'android/architecture-execution-trace',
        {
          type: 'category',
          label: 'Processes, Startup, and ART',
          collapsed: true,
          items: [
            'android/processes-startup',
            'android/zygote-process-creation',
            'android/startup-performance',
            'android/process-death-state',
            'android/art-dex-runtime',
            'android/art-compilation-profiles',
            'android/art-memory-gc',
            'android/baseline-startup-profiles',
            'android/runtime-interview',
          ],
        },
        {
          type: 'category',
          label: 'Binder and Android IPC',
          collapsed: true,
          items: [
            'android/binder-ipc',
            'android/binder-call-path',
            'android/aidl-practical',
            'android/binder-threading',
            'android/binder-failures-security',
            'android/binder-interview',
          ],
        },
        {
          type: 'category',
          label: 'Components and Lifecycle',
          collapsed: true,
          items: [
            'android/components-lifecycle',
            'android/activities-tasks',
            'android/fragments',
            'android/intents-results',
            'android/context-lifetimes',
            'android/components-interview',
          ],
        },
        {
          type: 'category',
          label: 'Resources and Compatibility',
          collapsed: true,
          items: [
            'android/resources-configuration',
            'android/density-dp-sp',
            'android/configuration-state',
            'android/localization-rtl',
            'android/manifest-compatibility',
            'android/resources-interview',
          ],
        },
        {
          type: 'category',
          label: 'Gradle and Release Builds',
          collapsed: true,
          items: [
            'android/gradle-build-system',
            'android/gradle-lifecycle-tasks',
            'android/agp-variants',
            'android/gradle-dependencies',
            'android/r8-release-optimization',
            'android/signing-artifacts',
            'android/build-performance-interview',
          ],
        },
        'android/platform-interview',
      ],
    },
    {
      type: 'category',
      label: 'Part III - UI Engineering',
      collapsed: true,
      items: [
        {
          type: 'category',
          label: 'View System and RecyclerView',
          collapsed: true,
          items: [
            'ui/views-rendering',
            'ui/xml-layouts',
            'ui/custom-views-touch',
            'ui/recyclerview',
            'ui/recyclerview-advanced',
            'ui/views-interview',
          ],
        },
        {
          type: 'category',
          label: 'Jetpack Compose Foundations',
          collapsed: true,
          items: [
            'ui/compose-foundations',
            'ui/compose-recomposition',
            'ui/compose-modifiers-layout',
            'ui/compose-material-theme',
            'ui/compose-lazy-lists',
            'ui/compose-input-interop',
            'ui/compose-foundations-interview',
          ],
        },
        {
          type: 'category',
          label: 'Compose State and Side Effects',
          collapsed: true,
          items: [
            'ui/compose-state-udf',
            'ui/compose-state-saving',
            'ui/compose-derived-stability',
            'ui/compose-side-effects',
            'ui/compose-flow-lifecycle',
            'ui/compose-state-interview',
          ],
        },
        {
          type: 'category',
          label: 'Advanced Compose',
          collapsed: true,
          items: [
            'ui/compose-custom-layouts',
            'ui/compose-animation',
            'ui/compose-semantics-accessibility',
            'ui/compose-performance',
            'ui/compose-design-systems',
            'ui/compose-navigation-adaptive',
            'ui/compose-testing-advanced',
          ],
        },
        {
          type: 'category',
          label: 'Inclusive and Adaptive UI',
          collapsed: true,
          items: [
            'ui/inclusive-accessibility',
            'ui/localization-rtl',
            'ui/adaptive-window-layouts',
            'ui/foldables-multiwindow',
            'ui/large-screen-input',
            'ui/inclusive-adaptive-interview',
          ],
        },
        'roadmap',
      ],
    },
    {
      type: 'category',
      label: 'Part IV - Application Architecture',
      collapsed: true,
      items: [
        {
          type: 'category',
          label: 'Architecture Foundations',
          collapsed: true,
          items: [
            'architecture/boundaries-coupling-cohesion',
            'architecture/solid-android',
            'architecture/mvc-mvp-mvvm-mvi',
            'architecture/udf-state-machines',
            'architecture/clean-architecture',
            'architecture/architecture-foundations-interview',
          ],
        },
        {
          type: 'category',
          label: 'Android Architecture Components',
          collapsed: true,
          items: [
            'architecture/viewmodel-scope',
            'architecture/savedstate-reconstruction',
            'architecture/lifecycle-concurrency',
            'architecture/navigation-architecture',
            'architecture/repository-usecase-ssot',
            'architecture/architecture-components-interview',
          ],
        },
        {
          type: 'category',
          label: 'Dependency Injection',
          collapsed: true,
          items: [
            'architecture/di-inversion-manual',
            'architecture/dagger-graph',
            'architecture/hilt-components',
            'architecture/assisted-runtime-di',
            'architecture/di-multibinding',
            'architecture/di-testing-performance',
            'architecture/di-interview',
          ],
        },
        {
          type: 'category',
          label: 'Design Patterns for Android',
          collapsed: true,
          items: [
            'architecture/patterns-creational',
            'architecture/patterns-structural',
            'architecture/patterns-behavioral',
            'architecture/patterns-coordination',
            'architecture/patterns-application-resilience',
            'architecture/patterns-interview',
          ],
        },
        {
          type: 'category',
          label: 'Modularization and Enterprise Scale',
          collapsed: true,
          items: [
            'architecture/modularization-strategy',
            'architecture/module-api-implementation',
            'architecture/module-dependency-build',
            'architecture/dynamic-feature-delivery',
            'architecture/modular-navigation-di',
            'architecture/module-ownership-monorepo',
            'architecture/modular-testing-interview',
          ],
        },
        'roadmap',
      ],
    },
    {
      type: 'category',
      label: 'Part V - Data, Networking, and Offline First',
      collapsed: true,
      items: [
        {
          type: 'category',
          label: 'Local Persistence',
          collapsed: true,
          items: [
            'data/sqlite-schema',
            'data/room-modeling-dao',
            'data/room-migrations',
            'data/room-transactions-flow-performance',
            'data/datastore',
            'data/persistence-selection',
            'data/persistence-interview',
          ],
        },
        {
          type: 'category',
          label: 'Repository and Data-Layer Design',
          collapsed: true,
          items: [
            'data/repository-boundaries',
            'data/local-remote-sources',
            'data/data-mapping',
            'data/freshness-errors-retries',
            'data/usecase-orchestration',
            'data/ssot-reactive-interview',
          ],
        },
        {
          type: 'category',
          label: 'Networking',
          collapsed: true,
          items: [
            'data/http-semantics',
            'data/retrofit-contracts',
            'data/okhttp-execution',
            'data/json-evolution',
            'data/network-streaming',
            'data/realtime-networking',
            'data/network-security',
            'data/networking-interview',
          ],
        },
        {
          type: 'category',
          label: 'Offline-First and Synchronization',
          collapsed: true,
          items: [
            'data/offline-readable-truth',
            'data/offline-write-strategies',
            'data/sync-queue-idempotency',
            'data/sync-conflicts',
            'data/sync-tombstones-cursors',
            'data/connectivity-multidevice',
            'data/offline-first-interview',
          ],
        },
        {
          type: 'category',
          label: 'Paging 3',
          collapsed: true,
          items: [
            'data/paging-foundations',
            'data/paging-remote-mediator',
            'data/paging-transform-cache',
            'data/paging-loadstates',
            'data/paging-testing-interview',
          ],
        },
        'roadmap',
      ],
    },
    {
      type: 'category',
      label: 'Part VI - Background Work and Device Capabilities',
      collapsed: true,
      items: [
        {
          type: 'category',
          label: 'Background Execution',
          collapsed: true,
          items: [
            'background/execution-choice',
            'background/workmanager-basics',
            'background/workmanager-chains',
            'background/worker-di-testing',
            'background/services',
            'background/foreground-services',
            'background/alarms-doze',
            'background/durability-interview',
          ],
        },
        {
          type: 'category',
          label: 'Notifications and External Entry Points',
          collapsed: true,
          items: [
            'background/notifications',
            'background/pending-intents',
            'background/deep-app-links',
            'background/cold-start-routing',
            'background/fcm',
            'background/notifications-interview',
          ],
        },
        {
          type: 'category',
          label: 'Permissions, Storage, Files, and Media',
          collapsed: true,
          items: [
            'device/permissions',
            'device/storage-model',
            'device/shared-content',
            'device/file-io',
            'device/media3-playback',
            'device/capture-audio-session',
            'device/storage-media-interview',
          ],
        },
        {
          type: 'category',
          label: 'Location and Maps',
          collapsed: true,
          items: [
            'device/location-permissions',
            'device/location-requests',
            'device/geofencing',
            'device/maps-architecture',
            'device/location-privacy',
            'device/location-maps-interview',
          ],
        },
        {
          type: 'category',
          label: 'BLE, NFC, Sensors, and Camera',
          collapsed: true,
          items: [
            'device/ble-discovery-gatt',
            'device/ble-connections',
            'device/nfc',
            'device/sensors',
            'device/camerax-pipeline',
            'device/capabilities-testing',
            'device/hardware-interview',
          ],
        },
        'roadmap',
      ],
    },
    {
      type: 'category',
      label: 'Part VII - Security and Privacy',
      collapsed: true,
      items: [
        {
          type: 'category',
          label: 'Android Application Security',
          collapsed: true,
          items: [
            'security/threat-modeling',
            'security/components-intents',
            'security/keystore',
            'security/cryptography',
            'security/network-security',
            'security/webview',
            'security/input-logging',
            'security/integrity-tamper',
            'security/security-interview',
          ],
        },
        {
          type: 'category',
          label: 'Authentication and Authorization',
          collapsed: true,
          items: [
            'security/oauth-oidc',
            'security/pkce-flow',
            'security/token-lifecycle',
            'security/okhttp-refresh',
            'security/biometrics',
            'security/session-multiaccount',
            'security/authorization',
            'security/auth-interview',
          ],
        },
        {
          type: 'category',
          label: 'Privacy Engineering',
          collapsed: true,
          items: [
            'security/privacy-by-design',
            'security/permission-transparency',
            'security/analytics-identifiers-sdks',
            'security/privacy-exposure',
            'security/privacy-rights-operations',
            'security/privacy-review-interview',
          ],
        },
        'roadmap',
      ],
    },
    {
      type: 'category',
      label: 'Part VIII - Performance, Reliability, and Quality',
      collapsed: true,
      items: [
        {
          type: 'category',
          label: 'Performance and Memory',
          collapsed: true,
          items: [
            'performance/measurement',
            'performance/profiling-tools',
            'performance/memory-leaks',
            'performance/bitmaps-large-objects',
            'performance/startup',
            'performance/anr-main-thread',
            'performance/jank-compose',
            'performance/battery-power',
            'performance/performance-interview',
          ],
        },
        {
          type: 'category',
          label: 'Testing Strategy',
          collapsed: true,
          items: [
            'testing/test-portfolio',
            'testing/test-levels-contracts',
            'testing/testable-architecture',
            'testing/test-doubles',
            'testing/coroutines-flow',
            'testing/data-background-tests',
            'testing/view-ui-runtimes',
            'testing/compose-visual-accessibility',
            'testing/quality-flakes-reports',
            'testing/testing-interview',
          ],
        },
        {
          type: 'category',
          label: 'Observability and Operational Reliability',
          collapsed: true,
          items: [
            'observability/structured-logging',
            'observability/crash-symbolication',
            'observability/analytics-contracts',
            'observability/traces-metrics',
            'observability/offline-telemetry',
            'observability/slos-incidents',
            'observability/firebase-operations',
            'observability/observability-interview',
          ],
        },
        {
          type: 'category',
          label: 'Feature Flags and Experimentation',
          collapsed: true,
          items: [
            'observability/feature-flag-types',
            'observability/flag-evaluation',
            'observability/kill-switch-config',
            'observability/flag-lifecycle-testing',
            'observability/experimentation',
            'observability/flags-interview',
          ],
        },
        'roadmap',
      ],
    },
    {
      type: 'category',
      label: 'Part IX - Delivery and Platform Expansion',
      collapsed: true,
      items: [
        {
          type: 'category',
          label: 'CI/CD and Release Engineering',
          collapsed: true,
          items: [
            'delivery/ci-pipeline',
            'delivery/build-speed-devices',
            'delivery/variants-secrets',
            'delivery/signing',
            'delivery/artifacts-tracks',
            'delivery/release-rollout',
            'delivery/release-interview',
          ],
        },
        {
          type: 'category',
          label: 'API and Android-version Compatibility',
          collapsed: true,
          items: [
            'delivery/sdk-levels',
            'delivery/api-checks',
            'delivery/target-behavior',
            'delivery/androidx-desugaring',
            'delivery/device-oem-compatibility',
            'delivery/compat-sensitive-apis',
            'delivery/compatibility-interview',
          ],
        },
        {
          type: 'category',
          label: 'Migration and Refactoring',
          collapsed: true,
          items: [
            'delivery/migration-strategy',
            'delivery/java-kotlin-migration',
            'delivery/views-compose-migration',
            'delivery/state-di-migration',
            'delivery/modularization-migration',
            'delivery/data-contract-migration',
            'delivery/migration-interview',
          ],
        },
        {
          type: 'category',
          label: 'Beyond the Standard Phone Application',
          collapsed: true,
          items: [
            'platform/automotive',
            'platform/ndk-jni',
            'platform/native-delivery',
            'platform/kmp-architecture',
            'platform/compose-multiplatform',
            'platform/platform-expansion-interview',
          ],
        },
        'roadmap',
      ],
    },
    {
      type: 'category',
      label: 'Part X - Android Architect Mastery',
      collapsed: true,
      items: [
        {
          type: 'category',
          label: 'Engineering Standards and Technical Leadership',
          collapsed: true,
          items: [
            'architect/standards-apis',
            'architect/code-review',
            'architect/quality-gates',
            'architect/technical-debt',
            'architect/technical-leadership',
            'architect/build-vs-buy',
            'architect/leadership-interview',
          ],
        },
        {
          type: 'category',
          label: 'Architecture Decisions and Trade-offs',
          collapsed: true,
          items: [
            'architect/decision-context',
            'architect/adrs',
            'architect/reversibility',
            'architect/tradeoff-cost',
            'architect/evolution-fitness',
            'architect/architecture-fashion',
            'architect/decisions-interview',
          ],
        },
        {
          type: 'category',
          label: 'Scalable Mobile Architecture',
          collapsed: true,
          items: [
            'architect/team-ownership',
            'architect/contracts-versioning',
            'architect/design-infrastructure',
            'architect/cross-feature-platform',
            'architect/offline-at-scale',
            'architect/budgets-governance',
            'architect/multibrand',
            'architect/enterprise',
            'architect/scalability-interview',
          ],
        },
        {
          type: 'category',
          label: 'System-design Case Studies',
          collapsed: true,
          items: [
            'case-studies/system-design-method',
            'case-studies/offline-commerce',
            'case-studies/chat-presence',
            'case-studies/secure-banking',
            'case-studies/ride-tracking',
            'case-studies/media-streaming',
            'case-studies/news-feed',
            'case-studies/ble-health',
            'case-studies/super-app',
          ],
        },
        {
          type: 'category',
          label: 'Interview Preparation',
          collapsed: true,
          items: [
            'interview/interview-method',
            'interview/kotlin-coroutines',
            'interview/platform-components',
            'interview/ui-interviews',
            'interview/architecture-data',
            'interview/quality-interviews',
            'interview/debugging-scenarios',
            'interview/architect-interview',
            'interview/resume-leadership',
            'interview/mock-scorecards',
          ],
        },
        'roadmap',
      ],
    },
  ],
};

export default sidebars;
